In [40]:

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

df = pd.read_csv(r"C:\\Contents\\Kaggle\\international-football-results-from-1872-to-2017\\results.csv")

df.head()

date home_team away_team  home_score  away_score tournament     city  \
0  1872-11-30  Scotland   England           0           0   Friendly  Glasgow   
1  1873-03-08   England  Scotland           4           2   Friendly   London   
2  1874-03-07  Scotland   England           2           1   Friendly  Glasgow   
3  1875-03-06   England  Scotland           2           2   Friendly   London   
4  1876-03-04  Scotland   England           3           0   Friendly  Glasgow   

    country  neutral  
0  Scotland    False  
1   England    False  
2  Scotland    False  
3   England    False  
4  Scotland    False

In [41]:
df.date=df.date.apply(lambda x: x.split('-')[0])

In [42]:
catcols = ['home_team','away_team','tournament', 'city', 'country','neutral']
df = pd.get_dummies(df, columns=catcols)
df.head()


date  home_score  away_score  home_team_Abkhazia  home_team_Afghanistan  \
0  1872           0           0                   0                      0   
1  1873           4           2                   0                      0   
2  1874           2           1                   0                      0   
3  1875           2           2                   0                      0   
4  1876           3           0                   0                      0   

   home_team_Albania  home_team_Alderney  home_team_Algeria  \
0                  0                   0                  0   
1                  0                   0                  0   
2                  0                   0                  0   
3                  0                   0                  0   
4                  0                   0                  0   

   home_team_American Samoa  home_team_Andalusia  ...  country_Yemen AR  \
0                         0                    0  ...                 0   
1                         0                    0  ...                 0   
2                         0                    0  ...                 0   
3                         0                    0  ...                 0   
4                         0                    0  ...                 0   

   country_Yemen DPR  country_Yugoslavia  country_Zambia  country_Zanzibar  \
0                  0                   0               0                 0   
1                  0                   0               0                 0   
2                  0                   0               0                 0   
3                  0                   0               0                 0   
4                  0                   0               0                 0   

   country_Zaïre  country_Zimbabwe  country_Éire  neutral_False  neutral_True  
0              0                 0             0              1             0  
1              0                 0             0              1             0  
2              0                 0             0              1             0  
3              0                 0             0              1             0  
4              0                 0             0              1             0  

[5 rows x 3009 columns]

In [43]:
df.columns

Index(['date', 'home_score', 'away_score', 'home_team_Abkhazia',
       'home_team_Afghanistan', 'home_team_Albania', 'home_team_Alderney',
       'home_team_Algeria', 'home_team_American Samoa', 'home_team_Andalusia',
       ...
       'country_Yemen AR', 'country_Yemen DPR', 'country_Yugoslavia',
       'country_Zambia', 'country_Zanzibar', 'country_Zaïre',
       'country_Zimbabwe', 'country_Éire', 'neutral_False', 'neutral_True'],
      dtype='object', length=3009)

In [44]:
def getResult(h,a):
    h,a= int(h), int(a)
    if h==a:
        return 0
    elif h>a:
        return 1
    return 2

df['Result'] = df.apply(lambda row: getResult(row['home_score'], row['away_score']), axis=1)

In [45]:
df.head()

date  home_score  away_score  home_team_Abkhazia  home_team_Afghanistan  \
0  1872           0           0                   0                      0   
1  1873           4           2                   0                      0   
2  1874           2           1                   0                      0   
3  1875           2           2                   0                      0   
4  1876           3           0                   0                      0   

   home_team_Albania  home_team_Alderney  home_team_Algeria  \
0                  0                   0                  0   
1                  0                   0                  0   
2                  0                   0                  0   
3                  0                   0                  0   
4                  0                   0                  0   

   home_team_American Samoa  home_team_Andalusia  ...  country_Yemen DPR  \
0                         0                    0  ...                  0   
1                         0                    0  ...                  0   
2                         0                    0  ...                  0   
3                         0                    0  ...                  0   
4                         0                    0  ...                  0   

   country_Yugoslavia  country_Zambia  country_Zanzibar  country_Zaïre  \
0                   0               0                 0              0   
1                   0               0                 0              0   
2                   0               0                 0              0   
3                   0               0                 0              0   
4                   0               0                 0              0   

   country_Zimbabwe  country_Éire  neutral_False  neutral_True  Result  
0                 0             0              1             0       0  
1                 0             0              1             0       1  
2                 0             0              1             0       1  
3                 0             0              1             0       0  
4                 0             0              1             0       1  

[5 rows x 3010 columns]

In [46]:
from sklearn.model_selection import train_test_split
feature_col_names = [col for col in df.columns if col not in set(['home_score','away_score','Result'])]
predicted_class_names = ['Result']

X = df[feature_col_names].values

Y = df[predicted_class_names].values

split_test_size = 0.25

X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size=split_test_size, random_state = 42)


In [47]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [48]:
from sklearn.naive_bayes import GaussianNB
nb_model = GaussianNB()
nb_model.fit(X_train, y_train.ravel())

nb_predict_train = nb_model.predict(X_train)
nb_predict_test = nb_model.predict(X_test)

from sklearn import metrics

print("NB Accuracy training : {0:.4f}".format(metrics.accuracy_score(y_train,nb_predict_train )))
print("NB Accuracy testing : {0:.4f}".format(metrics.accuracy_score(y_test,nb_predict_test )))
print('**********Confusion metrics**************')
print("{}".format(metrics.confusion_matrix(y_test, nb_predict_test)))
print('**********Classsification report**************')
print("{}".format(metrics.classification_report(y_test, nb_predict_test)))

NB Accuracy training : 0.3018
NB Accuracy testing : 0.2600
**********Confusion metrics**************
[[2152   55  183]
 [4436  158  471]
 [2502   47  393]]
**********Classsification report**************
              precision    recall  f1-score   support

           0       0.24      0.90      0.37      2390
           1       0.61      0.03      0.06      5065
           2       0.38      0.13      0.20      2942

    accuracy                           0.26     10397
   macro avg       0.41      0.36      0.21     10397
weighted avg       0.46      0.26      0.17     10397



In [49]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(random_state = 42)
rf_model.fit(X_train, y_train.ravel())

rf_predict_train = rf_model.predict(X_train)
rf_predict_test = rf_model.predict(X_test)

from sklearn import metrics

print("RF Accuracy training : {0:.4f}".format(metrics.accuracy_score(y_train,rf_predict_train )))
print("RF Accuracy testing : {0:.4f}".format(metrics.accuracy_score(y_test,rf_predict_test )))
print('********** RF Confusion metrics**************')
print("{}".format(metrics.confusion_matrix(y_test, rf_predict_test)))
print('**********RF Classsification report**************')
print("{}".format(metrics.classification_report(y_test, rf_predict_test)))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RF Accuracy training : 0.9650
RF Accuracy testing : 0.4983
********** RF Confusion metrics**************
[[ 566 1295  529]
 [ 894 3514  657]
 [ 673 1168 1101]]
**********RF Classsification report**************
              precision    recall  f1-score   support

           0       0.27      0.24      0.25      2390
           1       0.59      0.69      0.64      5065
           2       0.48      0.37      0.42      2942

    accuracy                           0.50     10397
   macro avg       0.44      0.43      0.44     10397
weighted avg       0.48      0.50      0.49     10397



In [50]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression()
lr_model.fit(X_train, y_train.ravel())
lr_predict_train = lr_model.predict(X_train)
lr_predict_test = lr_model.predict(X_test)

from sklearn import metrics

print("LR Accuracy training : {0:.4f}".format(metrics.accuracy_score(y_train,lr_predict_train )))
print("LR Accuracy testing : {0:.4f}".format(metrics.accuracy_score(y_test,lr_predict_test )))
print('********** LR Confusion metrics**************')
print("{}".format(metrics.confusion_matrix(y_test, lr_predict_test)))
print('**********LR Classsification report**************')
print("{}".format(metrics.classification_report(y_test, lr_predict_test)))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LR Accuracy training : 0.6143
LR Accuracy testing : 0.5645
********** LR Confusion metrics**************
[[ 182 1554  654]
 [ 212 4193  660]
 [ 222 1226 1494]]
**********LR Classsification report**************
              precision    recall  f1-score   support

           0       0.30      0.08      0.12      2390
           1       0.60      0.83      0.70      5065
           2       0.53      0.51      0.52      2942

    accuracy                           0.56     10397
   macro avg       0.48      0.47      0.45     10397
weighted avg       0.51      0.56      0.51     10397



In [53]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

lda = LinearDiscriminantAnalysis()
lda.fit(X_train, y_train.ravel())
lda_predict_train = lda.predict(X_train)
lda_predict_test = lda.predict(X_test)

from sklearn import metrics

print("LDA Accuracy training : {0:.4f}".format(metrics.accuracy_score(y_train,lda_predict_train )))
print("LDA Accuracy testing : {0:.4f}".format(metrics.accuracy_score(y_test,lda_predict_test )))
print('********** LDA Confusion metrics**************')
print("{}".format(metrics.confusion_matrix(y_test, lda_predict_test)))
print('**********LDA Classsification report**************')
print("{}".format(metrics.classification_report(y_test, lda_predict_test)))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


LDA Accuracy training : 0.6225
LDA Accuracy testing : 0.5524
********** LDA Confusion metrics**************
[[ 326 1431  633]
 [ 426 3953  686]
 [ 387 1091 1464]]
**********LDA Classsification report**************
              precision    recall  f1-score   support

           0       0.29      0.14      0.18      2390
           1       0.61      0.78      0.69      5065
           2       0.53      0.50      0.51      2942

    accuracy                           0.55     10397
   macro avg       0.47      0.47      0.46     10397
weighted avg       0.51      0.55      0.52     10397



In [56]:
from xgboost.sklearn import XGBClassifier


xgb = XGBClassifier()
xgb.fit(X_train, y_train.ravel())
xgb_predict_train = xgb.predict(X_train)
xgb_predict_test = xgb.predict(X_test)

from sklearn import metrics

print("XGB Accuracy training : {0:.4f}".format(metrics.accuracy_score(y_train,xgb_predict_train )))
print("XGB Accuracy testing : {0:.4f}".format(metrics.accuracy_score(y_test,xgb_predict_test )))
print('********** XGB Confusion metrics**************')
print("{}".format(metrics.confusion_matrix(y_test, xgb_predict_test)))
print('**********XGB Classsification report**************')
print("{}".format(metrics.classification_report(y_test, xgb_predict_test)))

XGB Accuracy training : 0.5969
XGB Accuracy testing : 0.5477
********** XGB Confusion metrics**************
[[  75 1974  341]
 [  79 4667  319]
 [ 108 1882  952]]
**********XGB Classsification report**************
              precision    recall  f1-score   support

           0       0.29      0.03      0.06      2390
           1       0.55      0.92      0.69      5065
           2       0.59      0.32      0.42      2942

    accuracy                           0.55     10397
   macro avg       0.47      0.43      0.39     10397
weighted avg       0.50      0.55      0.47     10397



In [79]:
import numpy as np
from scipy import stats

a = np.array([
  xgb_predict_test,
    lda_predict_test,
    lr_predict_test,
    rf_predict_test,
    nb_predict_test
])

ensemble_test = stats.mode(a)

In [82]:
ensemble_test = np.array(ensemble_test[0])

In [83]:
print("Ensemble Accuracy testing : {0:.4f}".format(metrics.accuracy_score(y_test,ensemble_test )))
print('********** Ensemble Confusion metrics**************')
print("{}".format(metrics.confusion_matrix(y_test, ensemble_test)))
print('**********Ensemble Classsification report**************')
print("{}".format(metrics.classification_report(y_test, ensemble_test)))

Ensemble Accuracy testing : 0.5545
********** Ensemble Confusion metrics**************
[[ 400 1581  409]
 [ 433 4220  412]
 [ 481 1316 1145]]
**********Ensemble Classsification report**************
              precision    recall  f1-score   support

           0       0.30      0.17      0.22      2390
           1       0.59      0.83      0.69      5065
           2       0.58      0.39      0.47      2942

    accuracy                           0.55     10397
   macro avg       0.49      0.46      0.46     10397
weighted avg       0.52      0.55      0.52     10397

